spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: false  #设置开启热部署
  freemarker:
    suffix: .ftl   #设定ftl文件路径
    cache: false    #页面不加载缓存，修改即时生效
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.225:3306/weixinxiaochengxu?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: mysql    # Specify the DBMS
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /static/**
  jackson:
    default-property-inclusion: non_null
wechat:
  # 公众账号 -- 授权
  mpAppId: wx9c45e1659ef562b2  # 公众平台id
  mpAppSecret: 0d278388837bb83a1b7e6bc4e30671df # 公众平台密钥